### PR TITLE
XS✔ ◾ [docs] Add lets deploy docs

### PR DESCRIPTION
**Pull request by mustafaStakater**
❌ **Add a description.**

### CODE REVIEW

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-c134996c`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-575094d1`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-70a25780`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-1f5717c8`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-f10a2347`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-919f2560`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-dbe51ccf`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-b0625995`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-3d517390`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-08c94392`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-b80fc00f`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-150-a2cdbded`

**Review by AsfaMumtaz — APPROVED** [review]

**Pull request merged**
