### PR TITLE
XS✔ ◾ [docs] Update _sidebar.md

### PR DESCRIPTION
**Pull request by mustafaStakater**
❌ **Add a description.**

### CODE REVIEW

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-154-105e27bc`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-154-7dc7d3ab`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-154-351bcb1c`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-154-9529251f`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-154-458758e9`

**Review by MuneebAijaz — APPROVED** [review]

**Pull request merged**
