### PR TITLE
XS✔ ◾ Update docs

### PR DESCRIPTION
**Pull request by abdulhaseeb2**
Update docs by improving the contents of sections and images

### CODE REVIEW

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-09ae167e`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-150f9030`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-df94d4f2`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-bf2cba51`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-b36cecb6`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-64d9678b`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-51de305e`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-33f8f82b`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-111-707b2c5f`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
