### PR TITLE
XS✔ ◾ [docs] update devspaces docs

### PR DESCRIPTION
**Pull request by mustafaStakater**
❌ **Add a description.**

### CODE REVIEW

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-b09a6382`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-c3264508`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-f8a9050b`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-ea7dd805`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-aed884db`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-f127381d`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-d2a0bc4e`

**Review by KhizerJaan — APPROVED** [review]

**Review by MuneebAijaz — APPROVED** [review]

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-163-3a379e19`

**Review by bilalbokharee — APPROVED** [review]

**Pull request merged**
