### PR TITLE
XS✔ ◾ [docs] update-image-and-other-minor-issues

### PR DESCRIPTION
**Pull request by mustafaStakater**
❌ **Add a description.**

### CODE REVIEW

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-d83165bf`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-9756997a`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-a7290182`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-2f68d4cc`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-3c67496f`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-826d00b0`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-76be274d`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-164-9fceddc8`

**Review by MuneebAijaz — APPROVED** [review]

**Review by karl-johan-grahn — APPROVED** [review]

**Review by karl-johan-grahn — APPROVED** [review]

**Review by karl-johan-grahn — APPROVED** [review]

**Pull request merged**
