### PR TITLE
XS✔ ◾ add outline for showcase

### PR DESCRIPTION
**Pull request by AsfaMumtaz**
Add outline for showcase

### CODE REVIEW

**Comment by stakater-user** [comment]
@AsfaMumtaz Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-148-3c889229`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-148-0230a15d`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-148-9cb49e52`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-148-434dca5f`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull stakater/workshop-exercise:SNAPSHOT-PR-148-7371c468`

**Review by bilalbokharee — APPROVED** [review]

**Pull request merged**
